Resources:
  BeginningsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.beginningsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: beginningId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: beginningId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST