Resources:
  DarknessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.darknessTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: darknessId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: darknessId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST